version: '3.8'

services:
  # Node.js API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interior-design-api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./public/uploads:/usr/src/app/public/uploads
      - ./backups:/usr/src/app/backups
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Nginx for serving frontend and reverse proxy
  nginx:
    image: nginx:alpine
    container_name: interior-design-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ../client/build:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
